# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xscad.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'xscad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bxscad.proto\x12\x05xscad\"I\n\rActionRequest\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.xscad.Header\x12\x19\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x0b.xscad.Body\"D\n\x06Header\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x0b\n\x03\x62ob\x18\x03 \x01(\t\x12\r\n\x05\x61lice\x18\x04 \x01(\t\"9\n\x04\x42ody\x12\x1e\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\r.xscad.Action\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"|\n\x06\x41\x63tion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\nparameters\x18\x02 \x03(\x0b\x32\x1d.xscad.Action.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"1\n\x0e\x41\x63tionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32L\n\x0cXSCADService\x12<\n\rExecuteAction\x12\x14.xscad.ActionRequest\x1a\x15.xscad.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xscad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION_PARAMETERSENTRY']._loaded_options = None
  _globals['_ACTION_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONREQUEST']._serialized_start=22
  _globals['_ACTIONREQUEST']._serialized_end=95
  _globals['_HEADER']._serialized_start=97
  _globals['_HEADER']._serialized_end=165
  _globals['_BODY']._serialized_start=167
  _globals['_BODY']._serialized_end=224
  _globals['_ACTION']._serialized_start=226
  _globals['_ACTION']._serialized_end=350
  _globals['_ACTION_PARAMETERSENTRY']._serialized_start=301
  _globals['_ACTION_PARAMETERSENTRY']._serialized_end=350
  _globals['_ACTIONRESPONSE']._serialized_start=352
  _globals['_ACTIONRESPONSE']._serialized_end=401
  _globals['_XSCADSERVICE']._serialized_start=403
  _globals['_XSCADSERVICE']._serialized_end=479
# @@protoc_insertion_point(module_scope)
